// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package com.shun;

public final class TeacherProto {
  private TeacherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeacherOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .Student student_list = 3;
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    java.util.List<com.shun.StudentProto.Student> 
        getStudentListList();
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    com.shun.StudentProto.Student getStudentList(int index);
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    int getStudentListCount();
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    java.util.List<? extends com.shun.StudentProto.StudentOrBuilder> 
        getStudentListOrBuilderList();
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    com.shun.StudentProto.StudentOrBuilder getStudentListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public static final class Teacher extends
      com.google.protobuf.GeneratedMessage
      implements TeacherOrBuilder {
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Teacher(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Teacher defaultInstance;
    public static Teacher getDefaultInstance() {
      return defaultInstance;
    }

    public Teacher getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                studentList_ = new java.util.ArrayList<com.shun.StudentProto.Student>();
                mutable_bitField0_ |= 0x00000004;
              }
              studentList_.add(input.readMessage(com.shun.StudentProto.Student.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          studentList_ = java.util.Collections.unmodifiableList(studentList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shun.TeacherProto.internal_static_Teacher_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shun.TeacherProto.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shun.TeacherProto.Teacher.class, com.shun.TeacherProto.Teacher.Builder.class);
    }

    public static com.google.protobuf.Parser<Teacher> PARSER =
        new com.google.protobuf.AbstractParser<Teacher>() {
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Student student_list = 3;
    public static final int STUDENT_LIST_FIELD_NUMBER = 3;
    private java.util.List<com.shun.StudentProto.Student> studentList_;
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public java.util.List<com.shun.StudentProto.Student> getStudentListList() {
      return studentList_;
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public java.util.List<? extends com.shun.StudentProto.StudentOrBuilder> 
        getStudentListOrBuilderList() {
      return studentList_;
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public int getStudentListCount() {
      return studentList_.size();
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public com.shun.StudentProto.Student getStudentList(int index) {
      return studentList_.get(index);
    }
    /**
     * <code>repeated .Student student_list = 3;</code>
     */
    public com.shun.StudentProto.StudentOrBuilder getStudentListOrBuilder(
        int index) {
      return studentList_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      studentList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getStudentListCount(); i++) {
        if (!getStudentList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < studentList_.size(); i++) {
        output.writeMessage(3, studentList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < studentList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, studentList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shun.TeacherProto.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shun.TeacherProto.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shun.TeacherProto.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shun.TeacherProto.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shun.TeacherProto.Teacher prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shun.TeacherProto.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shun.TeacherProto.internal_static_Teacher_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shun.TeacherProto.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shun.TeacherProto.Teacher.class, com.shun.TeacherProto.Teacher.Builder.class);
      }

      // Construct using com.shun.TeacherProto.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStudentListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (studentListBuilder_ == null) {
          studentList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          studentListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shun.TeacherProto.internal_static_Teacher_descriptor;
      }

      public com.shun.TeacherProto.Teacher getDefaultInstanceForType() {
        return com.shun.TeacherProto.Teacher.getDefaultInstance();
      }

      public com.shun.TeacherProto.Teacher build() {
        com.shun.TeacherProto.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shun.TeacherProto.Teacher buildPartial() {
        com.shun.TeacherProto.Teacher result = new com.shun.TeacherProto.Teacher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (studentListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            studentList_ = java.util.Collections.unmodifiableList(studentList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.studentList_ = studentList_;
        } else {
          result.studentList_ = studentListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shun.TeacherProto.Teacher) {
          return mergeFrom((com.shun.TeacherProto.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shun.TeacherProto.Teacher other) {
        if (other == com.shun.TeacherProto.Teacher.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (studentListBuilder_ == null) {
          if (!other.studentList_.isEmpty()) {
            if (studentList_.isEmpty()) {
              studentList_ = other.studentList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureStudentListIsMutable();
              studentList_.addAll(other.studentList_);
            }
            onChanged();
          }
        } else {
          if (!other.studentList_.isEmpty()) {
            if (studentListBuilder_.isEmpty()) {
              studentListBuilder_.dispose();
              studentListBuilder_ = null;
              studentList_ = other.studentList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              studentListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStudentListFieldBuilder() : null;
            } else {
              studentListBuilder_.addAllMessages(other.studentList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getStudentListCount(); i++) {
          if (!getStudentList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shun.TeacherProto.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shun.TeacherProto.Teacher) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .Student student_list = 3;
      private java.util.List<com.shun.StudentProto.Student> studentList_ =
        java.util.Collections.emptyList();
      private void ensureStudentListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          studentList_ = new java.util.ArrayList<com.shun.StudentProto.Student>(studentList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.shun.StudentProto.Student, com.shun.StudentProto.Student.Builder, com.shun.StudentProto.StudentOrBuilder> studentListBuilder_;

      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public java.util.List<com.shun.StudentProto.Student> getStudentListList() {
        if (studentListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(studentList_);
        } else {
          return studentListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public int getStudentListCount() {
        if (studentListBuilder_ == null) {
          return studentList_.size();
        } else {
          return studentListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.shun.StudentProto.Student getStudentList(int index) {
        if (studentListBuilder_ == null) {
          return studentList_.get(index);
        } else {
          return studentListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder setStudentList(
          int index, com.shun.StudentProto.Student value) {
        if (studentListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentListIsMutable();
          studentList_.set(index, value);
          onChanged();
        } else {
          studentListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder setStudentList(
          int index, com.shun.StudentProto.Student.Builder builderForValue) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(com.shun.StudentProto.Student value) {
        if (studentListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentListIsMutable();
          studentList_.add(value);
          onChanged();
        } else {
          studentListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(
          int index, com.shun.StudentProto.Student value) {
        if (studentListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentListIsMutable();
          studentList_.add(index, value);
          onChanged();
        } else {
          studentListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(
          com.shun.StudentProto.Student.Builder builderForValue) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.add(builderForValue.build());
          onChanged();
        } else {
          studentListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addStudentList(
          int index, com.shun.StudentProto.Student.Builder builderForValue) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder addAllStudentList(
          Iterable<? extends com.shun.StudentProto.Student> values) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          super.addAll(values, studentList_);
          onChanged();
        } else {
          studentListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder clearStudentList() {
        if (studentListBuilder_ == null) {
          studentList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          studentListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public Builder removeStudentList(int index) {
        if (studentListBuilder_ == null) {
          ensureStudentListIsMutable();
          studentList_.remove(index);
          onChanged();
        } else {
          studentListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.shun.StudentProto.Student.Builder getStudentListBuilder(
          int index) {
        return getStudentListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.shun.StudentProto.StudentOrBuilder getStudentListOrBuilder(
          int index) {
        if (studentListBuilder_ == null) {
          return studentList_.get(index);  } else {
          return studentListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public java.util.List<? extends com.shun.StudentProto.StudentOrBuilder> 
           getStudentListOrBuilderList() {
        if (studentListBuilder_ != null) {
          return studentListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(studentList_);
        }
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.shun.StudentProto.Student.Builder addStudentListBuilder() {
        return getStudentListFieldBuilder().addBuilder(
            com.shun.StudentProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public com.shun.StudentProto.Student.Builder addStudentListBuilder(
          int index) {
        return getStudentListFieldBuilder().addBuilder(
            index, com.shun.StudentProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .Student student_list = 3;</code>
       */
      public java.util.List<com.shun.StudentProto.Student.Builder> 
           getStudentListBuilderList() {
        return getStudentListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.shun.StudentProto.Student, com.shun.StudentProto.Student.Builder, com.shun.StudentProto.StudentOrBuilder> 
          getStudentListFieldBuilder() {
        if (studentListBuilder_ == null) {
          studentListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.shun.StudentProto.Student, com.shun.StudentProto.Student.Builder, com.shun.StudentProto.StudentOrBuilder>(
                  studentList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          studentList_ = null;
        }
        return studentListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    static {
      defaultInstance = new Teacher(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Teacher)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rteacher.proto\032\rstudent.proto\"C\n\007Teache" +
      "r\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \001(\t\022\036\n\014student_l" +
      "ist\030\003 \003(\0132\010.StudentB\030\n\010com.shunB\014Teacher" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Teacher_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Teacher_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Teacher_descriptor,
              new String[] { "Id", "Name", "StudentList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shun.StudentProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
