/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kxw_jni_Demo01 */

#ifndef _Included_com_kxw_jni_Demo01
#define _Included_com_kxw_jni_Demo01
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kxw_jni_Demo01
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kxw_jni_Demo01_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
